# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

variables:
  xcworkspacename: 'KFCircleMenu'
  scheme: 'KFCircleMenuDemo'
  sdk: 'iphoneos'
  configuration: 'Release'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: '$(scheme)'
    sdk: '$(sdk)'
    configuration: '$(configuration)'
    xcWorkspacePath: '**/$(xcworkspacename).xcworkspace'
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    xcodeVersion: 'default' # Options: 8, 9, default, specifyPath

# Install Apple Certificate
# Install an Apple certificate required to build on a macOS agent
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'Innoways Limited.p12'
    certPwd: '21897016' # Optional
    keychain: 'default' # Options: default, temp, custom
    #keychainPassword: # Required when keychain == Custom || Keychain == Default
    #customKeychainPath: # Required when keychain == Custom
    #deleteCert: # Optional
    #deleteCustomKeychain: # Optional
    signingIdentity: 'com.innoways.*' # Optional
