# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode


variables:
  xcworkspacename: 'KFCircleMenu'
  scheme: 'KFCircleMenuDemo'
  sdk: 'iphoneos'
  configuration: 'Release'

# Install Apple Certificate
# Install an Apple certificate required to build on a macOS agent
steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: Innoways_Limited.p12
    certPwd: $(p12Password)
    #keychain: 'temp' # Options: default, temp, custom
    #keychainPassword: # Required when keychain == Custom || Keychain == Default
    #customKeychainPath: # Required when keychain == Custom
    #deleteCert: # Optional
    #deleteCustomKeychain: # Optional
    #signingIdentity: # Optional
- task: InstallAppleProvisioningProfile@1
  inputs:
    provProfileSecureFile: Innoways_AdHoc_Distribution.mobileprovision
- task: Xcode@5
  inputs:
    actions: 'archive'
    scheme: '$(scheme)'
    sdk: '$(sdk)'
    configuration: '$(configuration)'
    xcWorkspacePath: '**/$(xcworkspacename).xcworkspace'
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
    packageApp: false
    #xcodeDeveloperDir: # Optional
    #archivePath: # Optional
    #exportPath: 'output/$(SDK)/$(Configuration)' # Optional
    #exportOptions: 'auto' # Optional. Options: auto, plist, specify
    #exportMethod: 'development' # Required when exportOptions == Specify
    #exportTeamId: # Optional
    #exportOptionsPlist: # Required when exportOptions == Plist
    #exportArgs: # Optional
    #signingOption: 'nosign' # Optional. Options: nosign, default, manual, auto
    #signingIdentity: # Optional
    #provisioningProfileUuid: # Optional
    #provisioningProfileName: # Optional
    #teamId: # Optional
    #destinationPlatformOption: 'default' # Optional. Options: default, iOS, tvOS, macOS, custom
    #destinationPlatform: # Optional
    #destinationTypeOption: 'simulators' # Optional. Options: simulators, devices
    #destinationSimulators: 'iPhone 7' # Optional
    #destinationDevices: # Optional
    #args: # Optional
    #workingDirectory: # Optional
    #useXcpretty: # Optional
    #publishJUnitResults: # Optional
